apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.name }}-service
  labels:
    app: {{ .Release.name }}
    
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.containerPorts }}
  selector:
    app: {{ .Release.name }}
