name: Development CI
on: [push]
jobs:
  Test-Go-Code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.24
    
    - name: Test
      run: go test .

    - name: Build
      run: go build -o main main.go

    - name: Run
      run: ./main